# Site settings
title: TEMT
SEOTitle: 码农先生的博客 | TEMT
header-img: img/post-bg-desk.jpg
email: 1036401093@qq.com
description: "编程 阅读 写作 分享 静静思考"
keyword: "BY, BY Blog, 码农先生的博客, java, web"
url: "http://miracletaotao.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/MiracleTaoTao/miracletaotao.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "编程 阅读 写作 分享 静静思考"
sidebar-avatar: /img/我的公众号.jpg     # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
weibo_username:     5501186701
zhihu_username:     wu-lang-tao
github_username:    MiracleTaoTao
#facebook_username:  
jianshu_username:   a775ca955a4d
twitter_username:   TEMT19597145




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 'a2fd1b80ae2f01e0527125591c9c010b'

# Google Analytics
#ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
#ga_domain: taolangwu.cn               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "pexels",
        href: "https://www.pexels.com/"
    },{
        title: "薇薇",
        href: "http://www.vivianchen.cn/"
    },{
        title: "一辈子的码农先生",
        href: "https://me.csdn.net/m0_37344350"
    }
]
